<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nim</string>
	</array>
	<key>name</key>
	<string>Nim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A documentation comment.</string>
			<key>match</key>
			<string>(##\s*(TODO|todo)?).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.doc-comment.nim</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A regular comment</string>
			<key>match</key>
			<string>(#\s*(TODO|todo)?).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.comment.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>C</string>
			<key>name</key>
			<string>source.c.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{\.(emit:) ?(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\"\"\")\.?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\`</string>
							<key>end</key>
							<string>\`</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>assembly</string>
			<key>name</key>
			<string>source.asm.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(asm )(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\`</string>
							<key>end</key>
							<string>\`</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.asm</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>A nim procedure or method declaration</string>
			<key>name</key>
			<string>meta.proc.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(proc|method|template|macro|iterator|converter)\s+(\`([^\s\`]+)\`|(\w+))(\*)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.proc.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\=</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>Generic</string>
							<key>match</key>
							<string>\[\w+\]</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>comment</key>
							<string>Pattern</string>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\w+</string>
									<key>name</key>
									<string>entity.other.attribute-name.pattern.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>comment</key>
							<string>Parameters</string>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>\{</string>
									<key>comment</key>
									<string>Pattern</string>
									<key>end</key>
									<string>\}</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\w+</string>
											<key>name</key>
											<string>entity.other.attribute-name.pattern.nim</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>source.nim</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\.</string>
			<key>comment</key>
			<string>Pragmas</string>
			<key>end</key>
			<string>\.?\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>end</key>
					<string>\"</string>
					<key>name</key>
					<string>string.something.nim</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>entity.other.attribute-name.pragma.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>discard \"\"\"</string>
			<key>comment</key>
			<string>A discarded triple string literal comment</string>
			<key>end</key>
			<string>\"\"\"</string>
			<key>name</key>
			<string>comment.line.discarded.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A float literal</string>
			<key>match</key>
			<string>\b((\d[_\d]*\.[_\d]+([eE][\+\-]?\d[_\d]*)?)|([eE][\+\-]?\d[_\d]*))('[fF](32|64))?</string>
			<key>name</key>
			<string>constant.numeric.float.decimal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A hexadecimal literal</string>
			<key>match</key>
			<string>\b(0[xX]\h[_\h]*)('[iIuU](8|16|32|64))?</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A base-8 integer literal</string>
			<key>match</key>
			<string>\b(0o[0-7][_0-7]*)('[iIuUfF](8|16|32|64))?</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A base-2 integer literal</string>
			<key>match</key>
			<string>\b(0(b|B)[01][_01]*)('[iIuUfF](8|16|32|64))?</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A base-10 integer literal</string>
			<key>match</key>
			<string>\b(\d[_\d]*)('[iIuUfF](8|16|32|64))?</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language Constants.</string>
			<key>match</key>
			<string>\b(true|false|inf|nil)\b</string>
			<key>name</key>
			<string>constant.language.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords that affect program control flow or scope.</string>
			<key>match</key>
			<string>\b(block|break|case|continue|do|elif|else|end|except|finally|if|raise|return|try|when|while|yield)\b</string>
			<key>name</key>
			<string>keyword.control.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword boolean operators for expressions.</string>
			<key>match</key>
			<string>(\b(and|in|is|isnot|not|notin|or|xor)\b)</string>
			<key>name</key>
			<string>keyword.operator.boolean.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Generic operators for expressions.</string>
			<key>match</key>
			<string>(\b()\b|(=|\+|-|\*|/|&lt;|&gt;|@|\$|~|&amp;|%|!|\?|\^|\.|:|\\)+)</string>
			<key>name</key>
			<string>keyword.operator.nim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(for)\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>in keyword in a 'for' loop</string>
			<key>end</key>
			<string>\:()</string>
			<key>name</key>
			<string>meta.forloop.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.nim</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\w+\s+(in)\s+</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Import syntax</string>
			<key>match</key>
			<string>((import)\s+[\/\w]+,?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.nim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(from)\s+[\/\w]+\s+(?=import)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other keywords.</string>
			<key>match</key>
			<string>(\b(addr|as|atomic|bind|cast|const|converter|discard|distinct|div|enum|export|include|let|mixin|object|of|ptr|ref|shl|shr|static|type|var)\b)</string>
			<key>name</key>
			<string>keyword.other.nim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(var|let)\s*\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Destructure syntax</string>
			<key>end</key>
			<string>\)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Invalid and unused keywords.</string>
			<key>match</key>
			<string>(\b(generic|interface|lambda|out|shared|with|without)\b)</string>
			<key>name</key>
			<string>keyword.invalid.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Common functions</string>
			<key>match</key>
			<string>\b(len|high|low)\b</string>
			<key>name</key>
			<string>support.function.any-method.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built-in, concrete types.</string>
			<key>match</key>
			<string>\b(((uint|int|float)(8|16|32|64)?)|bool|string|auto|cstring|char|byte|tobject|typedesc|stmt|expr)\b</string>
			<key>name</key>
			<string>storage.type.concrete.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built-in, generic types.</string>
			<key>match</key>
			<string>\b(range|array|seq|tuple|natural|set|ref|ptr)\b</string>
			<key>name</key>
			<string>storage.type.generic.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function types</string>
			<key>match</key>
			<string>\b(proc|iterator|method|template|macro)\b</string>
			<key>name</key>
			<string>storage.type.function.nim</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Special types.</string>
			<key>match</key>
			<string>\b(openarray|varargs|void)\b</string>
			<key>name</key>
			<string>storage.type.generic.nim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"\"\"</string>
			<key>comment</key>
			<string>(Raw) Triple Quoted String</string>
			<key>end</key>
			<string>\"\"\"</string>
			<key>name</key>
			<string>string.quoted.triple.nim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>r\"</string>
			<key>comment</key>
			<string>Raw Double Quoted String</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.raw.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\"\"</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double Quoted String</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\([abenrclftv\\]|["']|[0-9])|x\h\h)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single quoted character literal</string>
			<key>match</key>
			<string>\'(\\\d{1,3}|\\?[^\n]?)\'</string>
			<key>name</key>
			<string>string.quoted.single.nim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([\w\`]+)\s*(?=\(|\[.+?\]\s*\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Call syntax</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Command syntax</string>
			<key>match</key>
			<string>(\w+)(?=\s+[\w](?!\w+((?!\n)\s)+))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.nim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)(?=\s+[\"\'\`])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.nim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>tmpl specifier</string>
			<key>match</key>
			<string>(tmpl(i)?)(?=( (nim|html|xml|js|css|glsl|md))?\"\"\")</string>
		</dict>
		<dict>
			<key>name</key>
			<string>source.nim.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(nim)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.nim</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.html.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(html)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.xml.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(xml)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.js.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(js)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.css.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(css)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.glsl.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(glsl)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.glsl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>source.markdown.embedded.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(md)(\"\"\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nim</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\"\"\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.syntax.nim</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\(</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)\{</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\$)(\$)(for|while|case|of|when|if|else|elif)( )</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nim</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.nim</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\{|\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>plain</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.nim</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>(?&lt;!\$)(\$[a-zA-Z0-9_]+)</string>
							<key>name</key>
							<string>keyword.operator.nim</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.markdown.multimarkdown</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nim</string>
	<key>uuid</key>
	<string>fa6f2c1c-dd3f-4bcd-b2be-d05312be4080</string>
</dict>
</plist>
