<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nimf</string>
	</array>
	<key>name</key>
	<string>Nim Source Code Filter</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^ *#</string>
			<key>end</key>
			<string>^(?! *#)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(end) (proc|func|method|template|macro|iterator|converter)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#main</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>asm-stmt-1</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([Rr])?(""")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.triple.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.triple.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|"""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.triple.nimscf punctuation.definition.string.end.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([Rr])(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|(")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:[ABCEFLNPRTVabceflnprtv"'\\]|\d+|[Xx]\h{2}|[Uu](?:\h{4}|\{\h+}))</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\</string>
							<key>name</key>
							<string>invalid.illegal.lone-escape.nimscf</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>asm-stmts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>asm\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(?=[^"Rr{\s])|(?&lt;=")</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pragmas</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#asm-stmt-1</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^ *#</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|]#</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.number-sign.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block-doc-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^ *#</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>##\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|]##</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-doc-comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#square-brackets</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.braces.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.braces.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.braces.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.parens.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>builtins</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bresult\b</string>
					<key>name</key>
					<string>variable.language.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?x:any|array|auto|bool|byte |c(?:double|float|u?(?:long(?:long)?|char|int|short)|longdouble|schar |size(?:_t)?|string(?:[Aa]rray)?) |char|float(?:32|64)?|iterable|lent|open[Aa]rray|owned|pointer|ptr|range|ref|se[qt] |sink|static|string|typed?|type[Dd]esc|u?int(?:8|16|32|64)?|untyped|varargs|void)\b</string>
					<key>name</key>
					<string>storage.type.primitive.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>calls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x: (?= (?: (?!(?:out|ptr|ref|tuple)\b) [A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+` ) (?:\[.*])? (?: \( |" |[ ]+ (?: [_\d"'`\[\(] |(?!\.|(?:\*?[ ]*)[:=]|=[^=])[-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔]+[^\-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔\s] |(?!as|asm|and|bind|break|concept|const|continue|converter |defer|discard|distinct|div|elif|else|end|except|export|finally|from|import |include|interface|is(?:not)?|let|macro|method|mixin|mod|(?:not)?in|of |raise|sh[lr]|template|using|while|yield|x?or)[A-Za-z\x80-\xff] |\{(?!\.) ) ) ) )</string>
					<key>end</key>
					<string>^(?! *#)|(?=[^\[\(`\w\x{80}-\x{ff}])|(?&lt;=["\)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?=[`_A-Za-z\x80-\xff])</string>
							<key>end</key>
							<string>^(?! *#)|(?=[^`_A-Za-z\x80-\xff])</string>
							<key>name</key>
							<string>entity.name.function.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#builtins</string>
								</dict>
								<dict>
									<key>match</key>
									<string>[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[:?</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.generic.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|]</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.generic.end.nimscf</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.function-call.nimscf meta.generic.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.arguments.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(\))</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.arguments.end.nimscf</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.function-call.arguments.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.parameter.function.nimscf</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.nimscf</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(?x: (?= (?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`) [ ]* [:=](?![-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔]) ) (?!(?x:addr|asm|bind|block|break|case|cast|concept|const|continue|converter |defer|discard|distinct|do|elif|else|end|enum|except|export|finally|for |from|func|if|import|include|interface|iterator|let|macro|method|mixin |object|of|out|proc|ptr|raise|ref|return|static|template|try|tuple|type |using|var|when|while|yield)\b ) ([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?:[ ]*(:))? )</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#triplestr_lit</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|("(?!"))|(\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.unclosed-string.nimscf</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.double.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>""</string>
									<key>name</key>
									<string>constant.character.escape.nimscf</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>characters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.character.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>'(?:[^\\']|(\\(?:[ABCEFLNRTVabceflnrtv"'\\]|\d+|[Xx]\h{2})))'</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'[^']+'</string>
					<key>name</key>
					<string>invalid.illegal.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comments</string>
				</dict>
			</array>
		</dict>
		<key>const-defs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(const) +(?=[A-Za-z\x80-\xff]|\(|`|_\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?: *(\*))?|(?=[^\(])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.constant.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#const-name</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^const\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|^(?!  |$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^  (?=[A-Za-z\x80-\xff]|\(|`|_\b)</string>
							<key>end</key>
							<string>^(?! *#)|([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?: *(\*))?|(?=[^\(])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.constant.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.nimscf</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#const-name</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>const-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(\))|(?=[^{_`,#A-Za-z\x80-\xff\s])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.end.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.constant.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.nimscf</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?: *(\*))?</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.nimscf</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pragmas</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#doc-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>do-stmts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bdo\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(-&gt;)|(?=[^\-\( ])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.annotation.return.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#param-list</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>doc-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-doc-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-doc-comments</string>
				</dict>
			</array>
		</dict>
		<key>fmt-strs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:(fmt)|(&amp;))(""")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.nimscf variable.function.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.triple.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.triple.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|"""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.triple.nimscf punctuation.definition.string.end.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>{{|}}</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(=?(?: *:[^}]*)?) *(})|(?="""[^"])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.format-spec.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.nimscf</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.embedded.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(fmt)(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.nimscf variable.function.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.triple.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|("(?!"))|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.end.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>{{|}}|""</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(=?(?: *:[^}]*)?) *(})|(\n)|(?=")</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.format-spec.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.nimscf</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.nimscf</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.embedded.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&amp;)(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|(")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.end.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>{{|}}</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(=?(?: *:[^}]*)?) *(})|(\n)|(?=")</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.format-spec.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.nimscf</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.nimscf</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.embedded.nimscf</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\(?:[ABCEFLNPRTVabceflnprtv"'\\]|\d+|[Xx]\h{2}|[Uu](?:\h{4}|\{\h+}))</string>
									<key>name</key>
									<string>constant.character.escape.nimscf</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\</string>
									<key>name</key>
									<string>invalid.illegal.lone-escape.nimscf</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?:[ABCEFLNPRTVabceflnprtv"'\\]|\d+|[Xx]\h{2}|[Uu](?:\h{4}|\{\h+}))</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\</string>
							<key>name</key>
							<string>invalid.illegal.lone-escape.nimscf</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>for-stmt-1</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pragmas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>for-stmts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>for\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.loop.for.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(in\b)|(?=[^#,{_`A-Za-z\x80-\xff\s])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.loop.for.in.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.parens.begin.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(in\b)|(\))|(?=[^#,{_`A-Za-z\x80-\xff\s])</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.loop.for.in.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.parens.end.nimscf</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#for-stmt-1</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#for-stmt-1</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>generic-param-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=[`*\w\x{80}-\x{ff}]) *(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.generic.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(])|(?=[^#_`:=,;A-Za-z\x80-\xff\s])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.generic.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.generic.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generic-param-list-0</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>generic-param-list-0</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`</string>
					<key>name</key>
					<string>variable.parameter.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[,;]</string>
					<key>name</key>
					<string>punctuation.separator.nimscf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)|(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.annotation.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|([,;])|(?=\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>generic-symbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Z](_?[A-Z\d_])+\b</string>
					<key>name</key>
					<string>support.constant.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Z][\dA-Za-z]+\b</string>
					<key>name</key>
					<string>support.type.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>source.nimscf.embedded</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(`) *(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_) *(`)</string>
				</dict>
			</array>
		</dict>
		<key>invalid-names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x:addr|asm|bind|block|break|case|cast|concept|const|continue|converter |defer|discard|distinct|do|elif|else|end|enum|except|export|finally|for |from|func|if|import|include|interface|iterator|let|macro|method|mixin |object|of|out|proc|ptr|raise|ref|return|static|template|try|tuple|type |using|var|when|while|yield)\b</string>
					<key>name</key>
					<string>invalid.illegal.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:addr|cast)\b</string>
					<key>name</key>
					<string>keyword.operator.word.nimscf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\bdiscard +"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|"""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:distinct|discard)\b</string>
					<key>name</key>
					<string>keyword.other.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:asm|end|break|continue|raise|return|yield)\b</string>
					<key>name</key>
					<string>keyword.control.flow.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:concept|enum|interface)\b</string>
					<key>name</key>
					<string>storage.type.nimscf</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(object)\b(?: *(of)\b)?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bwhile\b</string>
					<key>name</key>
					<string>keyword.control.loop.while.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bcase\b</string>
					<key>name</key>
					<string>keyword.control.conditional.switch.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^ *(of)\b</string>
					<key>name</key>
					<string>keyword.control.conditional.case.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bif\b</string>
					<key>name</key>
					<string>keyword.control.conditional.if.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bwhen\b</string>
					<key>name</key>
					<string>keyword.control.conditional.when.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\belif\b</string>
					<key>name</key>
					<string>keyword.control.conditional.elseif.nimscf</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.statement.conditional.else.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.conditional.else.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.conditional.else.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(else)\b(?: *(:))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.statement.exception.try.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.exception.try.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.exception.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(try)\b(?: *(:))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.statement.exception.finally.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.exception.finally.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.exception.finally.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(finally)\b(?: *(:))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.defer.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(defer)\b(?: *(:))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.block.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(block)\b(?:(?: *(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`))? *(:))?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:as|(?:ex|im)port|include|bind|mixin|from|except)\b</string>
					<key>name</key>
					<string>keyword.control.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:const|let|var|using)\b</string>
					<key>name</key>
					<string>storage.modifier.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>language-constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:true|false|nil)\b</string>
					<key>name</key>
					<string>constant.language.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>line-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^ #</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(#)(?: *(TODO|todo)\b)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.deprecated.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>line-doc-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^ *#</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>##</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|^(?! *#)|$\n?</string>
					<key>name</key>
					<string>comment.line.documentation.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#str_lits</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language-constants</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-defs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#const-defs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var-let-using-defs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pragmas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-doc-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for-stmts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#asm-stmts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#routines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fmt-strs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#do-stmts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#calls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtins</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic-symbols</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.float.decimal.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.decimal.nimscf</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.exponent.nimscf</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.exponent.nimscf</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(\d(?:_?\d)*) (?: (?: ((\.)\d(?:_?\d)*) ([Ee][-+]?\d(?:_?\d)*)? |([Ee][-+]?\d(?:_?\d)*) ) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[Ff](?:32|64)|[Dd]))? |('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[Ff](?:32|64)|[Dd])) ) )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.float.hexadecimal.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(0[Xx]) (\h(?:_?\h)*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|[Ff](?:32|64)) )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.float.octal.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(0o) ([0-7](?:_?[0-7])*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[Ff](?:32|64)|[Dd])) )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.float.binary.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(0[Bb]) ([01](?:_?[01])*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[Ff](?:32|64)|[Dd])) )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.integer.hexadecimal.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(0[Xx]) (\h(?:_?\h)*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[IUiu](?:8|16|32|64)|[Uu]))? )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.integer.octal.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(0o) ([0-7](?:_?[0-7])*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[IUiu](?:8|16|32|64)|[Uu]))? )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.integer.binary.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(0[Bb]) ([01](?:_?[01])*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[IUiu](?:8|16|32|64)|[Uu]))? )</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.number.integer.decimal.nimscf</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.suffix.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x: \b(\d(?:_?\d)*) ('(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_)|(?:[IUiu](?:8|16|32|64)|[Uu]))? )</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:and|not|x?or)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^of\b</string>
					<key>name</key>
					<string>keyword.control.conditional.case.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:of|(?:not)?in|is(?:not)?)\b</string>
					<key>name</key>
					<string>keyword.operator.word.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bsh[lr]\b</string>
					<key>name</key>
					<string>keyword.operator.bitwise.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:div|mod)\b</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>==|&lt;=?|&gt;=?|!=</string>
					<key>name</key>
					<string>keyword.operator.comparison.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:[-+*/@$&amp;%|^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔][-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔]*)?=(?![-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔])</string>
					<key>name</key>
					<string>keyword.operator.assignment.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔]+</string>
					<key>name</key>
					<string>keyword.operator.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>param-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parameters.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parameters.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.parameters</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`</string>
							<key>name</key>
							<string>variable.parameter.nimscf</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[,;]</string>
							<key>name</key>
							<string>punctuation.separator.nimscf</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(:)|(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.annotation.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(?=[,;\)])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#main</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{(?!\.)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.pattern.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.pattern.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.pattern.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>pragmas</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{\.(?!\.})</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.annotation.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|\.?}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.annotation.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.annotation.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`</string>
							<key>name</key>
							<string>entity.other.attribute-name.pragma.nimscf</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#square-brackets</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?=\S)</string>
							<key>end</key>
							<string>^(?! *#)|(,)|(?=\.?})</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.sequence.nimscf</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>:</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.key-value.nimscf</string>
										</dict>
									</dict>
									<key>end</key>
									<string>^(?! *#)|(,)|(?=\.?})</string>
									<key>endCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.sequence.nimscf</string>
										</dict>
									</dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#main</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>punctuations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.statement.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>punctuation.section.block.begin.nimscf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.(?![-=+*/&lt;&gt;@$~&amp;%|!?^.:\\∙∘×★⊗⊘⊙⊛⊠⊡∩∧⊓±⊕⊖⊞⊟∪∨⊔])</string>
					<key>name</key>
					<string>punctuation.accessor.dot.nimscf</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.annotation.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*) *(:|(?=,|#|\{\.))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\)|]|}</string>
					<key>name</key>
					<string>invalid.illegal.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>routines</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x: (proc|template|iterator|func|method|macro|converter)\b (?:[ ]*([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?:[ ]*(\*))?)? )</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(:)|(?=[^#\(\[:\s]|##)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.annotation.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#generic-param-list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#param-list</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>rstr_lit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([Rr])(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.double.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|("(?!"))|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf punctuation.definition.string.end.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.nimscf invalid.illegal.unclosed-string.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>""</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>square-brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.brackets.end.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.brackets.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>str_lit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.nimscf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.nimscf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:[ABCEFLNPRTVabceflnprtv"'\\]|\d+|[Xx]\h{2}|[Uu](?:\h{4}|\{\h+}))</string>
							<key>name</key>
							<string>constant.character.escape.nimscf</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\</string>
							<key>name</key>
							<string>invalid.illegal.lone-escape.nimscf</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>str_lits</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#triplestr_lit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rstr_lit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#str_lit</string>
				</dict>
			</array>
		</dict>
		<key>triplestr_lit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([Rr])?(""")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.triple.nimscf punctuation.definition.string.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.quoted.triple.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|"""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.triple.nimscf punctuation.definition.string.end.nimscf</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>type-defs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^ *(type) +(?:(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`) *(\.))?([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?: *(\*))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor.dot.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.nimscf</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(?=[^\[ ])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generic-param-list</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^type\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|^(?!  |$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^  (?:(?:[A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`) *(\.))?([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?: *(\*))?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.accessor.dot.nimscf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.nimscf</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.nimscf</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?! *#)|(?![\[\s])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#generic-param-list</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\btuple(?=\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.primitive.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(?=[^\[ ])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#generic-param-list</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=(?:[A-Za-z](?:_?[\dA-Za-z])*)\[)(?x:(out|ptr|ref|array |cstring[Aa]rray|iterable|lent|open[Aa]rray|owned|ptr|range|ref|se[qt] |sink|static|type(?:[Dd]esc)?|varargs)|([A-Z][\dA-Za-z]+))(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.primitive.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type.nimscf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.generic.nimscf punctuation.section.generic.begin.nimscf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.generic.nimscf</string>
					<key>end</key>
					<string>^(?! *#)|]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.generic.nimscf punctuation.section.generic.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:out|tuple|ref|ptr)\b</string>
					<key>name</key>
					<string>storage.type.primitive.nimscf</string>
				</dict>
			</array>
		</dict>
		<key>var-let-using-defs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^|(;)) *(var|let|using) +(?=[\(`A-Za-z\x80-\xff]|_\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(?=[^\({_`,#A-Za-z\x80-\xff\s])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#var-name</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?:var|let|using)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|^(?!  |$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^  (?=[\(`A-Za-z\x80-\xff]|_\b)</string>
							<key>end</key>
							<string>^(?! *#)|(?=[^\({_`,#A-Za-z\x80-\xff\s])</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#var-name</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.begin.nimscf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?! *#)|(\))|(?=[^{_`,#A-Za-z\x80-\xff\s])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.end.nimscf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#var-name-0</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#var-name-0</string>
				</dict>
			</array>
		</dict>
		<key>var-name-0</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.nimscf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.nimscf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z\x80-\xff](?:_?[\dA-Za-z\x80-\xff])*|_|`[^;,\n`]+`)(?: *(\*))?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.nimscf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pragmas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nimscf</string>
</dict>
</plist>
