<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Nim Comment</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i)(\#\[)\s*(todo\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.multi-comment.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A multiline comment.</string>
			<key>end</key>
			<string>(?i)(\]\#)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.multi-comment.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.number-sign.multi-comment.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\#\#\[)\s*(todo\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.multi-doc-comment.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A multiline documentation comment.</string>
			<key>end</key>
			<string>(?i)(\]\#\#)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.multi-doc-comment.nim</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.number-sign.multi-doc-comment.nim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doc-comment.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nim</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.doc-comment.body.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A documentation comment.</string>
			<key>match</key>
			<string>(?i)(##\s*)(todo\b)?(.*$\n?)</string>
			<key>name</key>
			<string>comment.line.number-sign.doc-comment.nim</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nim</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nim</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.comment.body.nim</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A regular comment</string>
			<key>match</key>
			<string>(?i)(#\s*)(todo\b)?(.*$\n?)</string>
			<key>name</key>
			<string>comment.line.number-sign.comment.nim</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nim.comment</string>
	<key>uuid</key>
	<string>fa6f2c1c-dd3f-4bcd-b2be-d05312be4081</string>
</dict>
</plist>
