/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IE:\Development\GitHub\Nimrod\lib -o "C:\Users\Erik\AppData\Roaming\Sublime Text 2\Packages\Nimrod-Sublime\nimcache\nimrod_system.o" "C:\Users\Erik\AppData\Roaming\Sublime Text 2\Packages\Nimrod-Sublime\nimcache\nimrod_system.c" */
#define NIM_INTBITS 32
/*	NIM_merge_HEADERS:*/

#include "nimbase.h"
/*	NIM_merge_END:*/

/*	NIM_merge_FORWARD_TYPES:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPES:*/
/*	NIM_merge_END:*/

/*	NIM_merge_SEQ_TYPES:*/
/*	NIM_merge_END:*/

/*	NIM_merge_FIELD_INFO:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPE_INFO:*/
/*	NIM_merge_END:*/

/*	NIM_merge_PROC_HEADERS:*/
/*	NIM_merge_END:*/

/*	NIM_merge_DATA:*/
/*	NIM_merge_END:*/

/*	NIM_merge_VARS:*/
/*	NIM_merge_END:*/

/*	NIM_merge_PROCS:*/
/*	NIM_merge_END:*/
N_NOINLINE(void, systemInit)(void) {

/*	NIM_merge_PROC_LOCALS:*/
/*	NIM_merge_END:*/
	TFrame F; F.len = 0;
/*	NIM_merge_PROC_INIT:*/
/*	NIM_merge_END:*/

/*	NIM_merge_PROC_BODY:*/
/*	NIM_merge_END:*/
}

N_NOINLINE(void, systemDatInit)(void) {

/*	NIM_merge_TYPE_INIT1:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPE_INIT2:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPE_INIT3:*/
/*	NIM_merge_END:*/

/*	NIM_merge_DEBUG_INIT:*/
/*	NIM_merge_END:*/

/*	NIM_merge_DYNLIB_INIT:*/
/*	NIM_merge_END:*/
}

