/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IE:\Development\GitHub\Nimrod\lib -o "C:\Users\Erik\AppData\Roaming\Sublime Text 2\Packages\Nimrod-Sublime\nimcache\nimrod-sublime_.o" "C:\Users\Erik\AppData\Roaming\Sublime Text 2\Packages\Nimrod-Sublime\nimcache\nimrod-sublime_.c" */
#define NIM_INTBITS 32
/*	NIM_merge_HEADERS:*/

#include "nimbase.h"
/*	NIM_merge_END:*/

/*	NIM_merge_FORWARD_TYPES:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPES:*/
/*	NIM_merge_END:*/

/*	NIM_merge_SEQ_TYPES:*/
/*	NIM_merge_END:*/

/*	NIM_merge_FIELD_INFO:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPE_INFO:*/
/*	NIM_merge_END:*/

/*	NIM_merge_PROC_HEADERS:*/
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
/*	NIM_merge_END:*/

/*	NIM_merge_DATA:*/
/*	NIM_merge_END:*/

/*	NIM_merge_VARS:*/
extern TFrame* frameptr_11825;
/*	NIM_merge_END:*/

/*	NIM_merge_PROCS:*/

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}/*	NIM_merge_END:*/
N_NOINLINE(void, .nimInit)(void) {

/*	NIM_merge_PROC_LOCALS:*/
/*	NIM_merge_END:*/
	nimfr(".nim", ".nim")

/*	NIM_merge_PROC_INIT:*/
/*	NIM_merge_END:*/

/*	NIM_merge_PROC_BODY:*/
/*	NIM_merge_END:*/
	popFrame();
}

N_NOINLINE(void, .nimDatInit)(void) {

/*	NIM_merge_TYPE_INIT1:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPE_INIT2:*/
/*	NIM_merge_END:*/

/*	NIM_merge_TYPE_INIT3:*/
/*	NIM_merge_END:*/

/*	NIM_merge_DEBUG_INIT:*/
/*	NIM_merge_END:*/

/*	NIM_merge_DYNLIB_INIT:*/
/*	NIM_merge_END:*/
}

